// Mocks generated by Mockito 5.4.4 from annotations
// in otzaria/test/text_book/editing/bloc/text_book_bloc_editor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:otzaria/models/books.dart' as _i4;
import 'package:otzaria/models/links.dart' as _i6;
import 'package:otzaria/text_book/editing/models/text_draft.dart' as _i9;
import 'package:otzaria/text_book/editing/models/text_override.dart' as _i8;
import 'package:otzaria/text_book/editing/repository/overrides_repository.dart'
    as _i7;
import 'package:otzaria/text_book/editing/services/overrides_rebase_service.dart'
    as _i10;
import 'package:otzaria/text_book/text_book_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TextBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextBookRepository extends _i1.Mock
    implements _i2.TextBookRepository {
  MockTextBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getBookContent(_i4.TextBook? book) => (super.noSuchMethod(
        Invocation.method(
          #getBookContent,
          [book],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getBookContent,
            [book],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<_i6.Link>> getBookLinks(_i4.TextBook? book) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookLinks,
          [book],
        ),
        returnValue: _i3.Future<List<_i6.Link>>.value(<_i6.Link>[]),
      ) as _i3.Future<List<_i6.Link>>);

  @override
  _i3.Future<List<_i4.TocEntry>> getTableOfContents(_i4.TextBook? book) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTableOfContents,
          [book],
        ),
        returnValue: _i3.Future<List<_i4.TocEntry>>.value(<_i4.TocEntry>[]),
      ) as _i3.Future<List<_i4.TocEntry>>);

  @override
  _i3.Future<List<String>> getAvailableCommentators(List<_i6.Link>? links) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCommentators,
          [links],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> bookExists(String? title) => (super.noSuchMethod(
        Invocation.method(
          #bookExists,
          [title],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveBookContent(
    _i4.TextBook? book,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBookContent,
          [
            book,
            content,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [OverridesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverridesRepository extends _i1.Mock
    implements _i7.OverridesRepository {
  MockOverridesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i8.TextOverride?> readOverride(
    String? bookId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readOverride,
          [
            bookId,
            sectionId,
          ],
        ),
        returnValue: _i3.Future<_i8.TextOverride?>.value(),
      ) as _i3.Future<_i8.TextOverride?>);

  @override
  _i3.Future<void> writeOverride(
    String? bookId,
    String? sectionId,
    String? markdown,
    String? sourceHash,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeOverride,
          [
            bookId,
            sectionId,
            markdown,
            sourceHash,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.TextDraft?> readDraft(
    String? bookId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readDraft,
          [
            bookId,
            sectionId,
          ],
        ),
        returnValue: _i3.Future<_i9.TextDraft?>.value(),
      ) as _i3.Future<_i9.TextDraft?>);

  @override
  _i3.Future<void> writeDraft(
    String? bookId,
    String? sectionId,
    String? markdown,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeDraft,
          [
            bookId,
            sectionId,
            markdown,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDraft(
    String? bookId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [
            bookId,
            sectionId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasNewerDraftThanOverride(
    String? bookId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasNewerDraftThanOverride,
          [
            bookId,
            sectionId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasLinksFile(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #hasLinksFile,
          [bookId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> listOverrides(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #listOverrides,
          [bookId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> listDrafts(String? bookId) => (super.noSuchMethod(
        Invocation.method(
          #listDrafts,
          [bookId],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> cleanupOldDrafts() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldDrafts,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<double> getTotalDraftsSizeMB() => (super.noSuchMethod(
        Invocation.method(
          #getTotalDraftsSizeMB,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<void> deleteOverride(
    String? bookId,
    String? sectionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOverride,
          [
            bookId,
            sectionId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [OverridesRebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverridesRebaseService extends _i1.Mock
    implements _i10.OverridesRebaseService {
  MockOverridesRebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i10.RebaseOutcome> rebaseIfSourceChanged({
    required String? bookId,
    required String? sectionId,
    required String? originalCandidate,
    required String? overrideMarkdown,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rebaseIfSourceChanged,
          [],
          {
            #bookId: bookId,
            #sectionId: sectionId,
            #originalCandidate: originalCandidate,
            #overrideMarkdown: overrideMarkdown,
          },
        ),
        returnValue:
            _i3.Future<_i10.RebaseOutcome>.value(_i10.RebaseOutcome.success),
      ) as _i3.Future<_i10.RebaseOutcome>);

  @override
  _i3.Future<_i10.RebaseContext?> getRebaseContext({
    required String? bookId,
    required String? sectionId,
    required String? newSourceContent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRebaseContext,
          [],
          {
            #bookId: bookId,
            #sectionId: sectionId,
            #newSourceContent: newSourceContent,
          },
        ),
        returnValue: _i3.Future<_i10.RebaseContext?>.value(),
      ) as _i3.Future<_i10.RebaseContext?>);
}
