// Mocks generated by Mockito 5.4.4 from annotations
// in otzaria/test/unit/mocks/mock_settings_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:otzaria/settings/settings_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  @override
  _i3.Future<Map<String, dynamic>> loadSettings() => (super.noSuchMethod(
        Invocation.method(
          #loadSettings,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> updateDarkMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateDarkMode,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSeedColor(_i4.Color? value) => (super.noSuchMethod(
        Invocation.method(
          #updateSeedColor,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTextMaxWidth(double? value) => (super.noSuchMethod(
        Invocation.method(
          #updateTextMaxWidth,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateFontSize(double? value) => (super.noSuchMethod(
        Invocation.method(
          #updateFontSize,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateFontFamily(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateFontFamily,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCommentatorsFontFamily(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCommentatorsFontFamily,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShowOtzarHachochma(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateShowOtzarHachochma,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShowHebrewBooks(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateShowHebrewBooks,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShowExternalBooks(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateShowExternalBooks,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShowTeamim(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateShowTeamim,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUseFastSearch(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateUseFastSearch,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateReplaceHolyNames(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateReplaceHolyNames,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAutoUpdateIndex(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateAutoUpdateIndex,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDefaultRemoveNikud(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateDefaultRemoveNikud,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRemoveNikudFromTanach(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRemoveNikudFromTanach,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDefaultSidebarOpen(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateDefaultSidebarOpen,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePinSidebar(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updatePinSidebar,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSidebarWidth(double? value) => (super.noSuchMethod(
        Invocation.method(
          #updateSidebarWidth,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateFacetFilteringWidth(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFacetFilteringWidth,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCommentaryPaneWidth(double? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCommentaryPaneWidth,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCalendarType(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateCalendarType,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSelectedCity(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateSelectedCity,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCalendarEvents(String? eventsJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarEvents,
          [eventsJson],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCopyWithHeaders(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateCopyWithHeaders,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCopyHeaderFormat(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateCopyHeaderFormat,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateIsFullscreen(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateIsFullscreen,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLibraryViewMode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #updateLibraryViewMode,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateLibraryShowPreview(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateLibraryShowPreview,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateEnablePerBookSettings(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnablePerBookSettings,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCalendarNotificationsEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarNotificationsEnabled,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCalendarNotificationTime(int? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarNotificationTime,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCalendarNotificationSound(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarNotificationSound,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> getShortcuts() => (super.noSuchMethod(
        Invocation.method(
          #getShortcuts,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> resetShortcuts() => (super.noSuchMethod(
        Invocation.method(
          #resetShortcuts,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateShortcut(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShortcut,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
